#ifndef KF_GAME_NOTIFY_TYPES_H
#define KF_GAME_NOTIFY_TYPES_H

#include <kf/lib/types.h>
#include <kf/lib/enum.h>

enum class KfNotificationId : u8 {
    KF_NOTIFICATION_LEVEL_UP = 0,
    KF_NOTIFICATION_1 = 1,
    KF_NOTIFICATION_4 = 4,
    KF_NOTIFICATION_6 = 6,
    KF_NOTIFICATION_16 = 16,

    KF_NOTIFICATION_CANNOT_CARRY_MORE = 18,

    KF_NOTIFICATION_NOTHING_HAPPENS = 20,
    KF_NOTIFICATION_PAYLOAD_ID = 21,
    KF_NOTIFICATION_22 = 22,
    KF_NOTIFICATION_PHYSICAL_POWER_INCREASED = 31,
    KF_NOTIFICATION_MAGIC_POWER_INCREASED = 32,

    KF_NOTIFICATION_EFFECT_EXPIRED = 34,
    KF_NOTIFICATION_MAX_QUEUED_ID = 239,
    KF_NOTIFICATION_NONE = 0xff
}; using enum KfNotificationId;

enum class KfNotificationPhase : u8 {
    KF_NOTIFICATION_IDLE = 0,
    KF_NOTIFICATION_FADE_IN = 1,
    KF_NOTIFICATION_HOLD = 2,
    KF_NOTIFICATION_FADE_OUT = 3
}; using enum KfNotificationPhase;

#endif
